[project]
name = "corncob"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "pyyaml>=6.0.3",
    "requests>=2.32.5",
]

[project.scripts]
corncob = "corncob.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
