[project]
name = "small-sea-team-manager"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "small-sea-client",
    "click>=8.0",
    "fastapi[standard]>=0.118.0",
    "jinja2>=3.1",
]

[project.scripts]
small-sea-teams = "small_sea_team_manager.cli:cli"

[tool.uv.sources]
small-sea-client = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
