[project]
name = "small-sea-team-manager"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "small-sea-client",
    "corncob",
    "click>=8.0",
    "cryptography>=46.0.3",
    "fastapi[standard]>=0.118.0",
    "jinja2>=3.1",
    "plyer>=2.1.0",
    "sqlalchemy>=2.0.44",
]

[project.scripts]
small-sea-teams = "small_sea_team_manager.cli:cli"

[tool.uv.sources]
small-sea-client = { workspace = true }
corncob = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
