[project]
name = "shared-file-vault"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "corncob",
    "click>=8.0",
    "fastapi[standard]>=0.118.0",
    "jinja2>=3.1",
    "sqlalchemy>=2.0.44",
]

[project.scripts]
shared-file-vault = "shared_file_vault.cli:cli"

[tool.uv.sources]
corncob = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
