[project]
name = "small-sea-client"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "click>=8.0",
    "requests>=2.32.5",
]

[project.scripts]
small-sea = "small_sea_client.cli:cli"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
